version: 0.2

phases:
  install:
    commands:
      - echo "******** Installing bundler ********"
      - gem install bundler
  pre_build:
    commands:
      - echo "******** Installing dependencies ********"
      - bundle install
      - echo "******** Making build.sh executable ********"
      - chmod u+x build.sh
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
  post_build:
    commands:
      # - echo "******** Uploading to S3 ********"
      # Use the --delete option to remove deleted local files from the S3 bucket
      - aws s3 sync _site/ s3://jekyll-site-demo --delete
      # Use a build scipt to deploy to staging or prodution. You must use `sh script.sh` vs `./script` or AWS will throw an Access Denied error
      # - sh build.sh
